name: Update Programmers Card

on:
  schedule:
    - cron: '0 15 * * *' # 매일 자정 업데이트
  workflow_dispatch: 

jobs:
  update-card:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Programmers Card
        uses: Yidadaa/programmers-card@master
        with:
          user_id: '472401'

      - name: Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update Programmers Card" || exit 0
          git push
